apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gamearr.fullname" . }}-env
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  {{- if .Values.postgres.enabled }}
  DB_URL: "{{ printf "postgres://%s:%s@%s-postgres:%d/%s" .Values.postgres.user .Values.postgres.password (include "gamearr.fullname" .) .Values.postgres.service.port .Values.postgres.database }}"
  {{- else }}
  DB_URL: {{ .Values.external.dbUrl | quote }}
  {{- end }}
  REDIS_URL: "redis://{{ include "gamearr.fullname" . }}-redis:{{ .Values.redis.service.port }}"
  VITE_API_URL: "http://{{ include "gamearr.fullname" . }}-api:{{ .Values.api.service.port }}"
  FRONTEND_URL: "http://{{ include "gamearr.fullname" . }}-web:{{ .Values.web.service.port }}"
