apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gamearr.fullname" . }}-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ include "gamearr.fullname" . }}-worker
  template:
    metadata:
      labels:
        app: {{ include "gamearr.fullname" . }}-worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: worker
          image: {{ .Values.worker.image }}
          envFrom:
            - secretRef:
                name: {{ include "gamearr.fullname" . }}-env
          livenessProbe:
            exec:
              command: ["node", "-e", "process.exit(0)"]
            initialDelaySeconds: 10
          readinessProbe:
            exec:
              command: ["node", "-e", "process.exit(0)"]
            initialDelaySeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
          resources: {{ toYaml .Values.worker.resources | nindent 12 }}
---
{{- if .Values.worker.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "gamearr.fullname" . }}-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "gamearr.fullname" . }}-worker
  minReplicas: {{ .Values.worker.hpa.minReplicas }}
  maxReplicas: {{ .Values.worker.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.worker.hpa.targetCPUUtilizationPercentage }}
{{- end }}
