services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      DB_URL: postgres://gamearr:${POSTGRES_PASSWORD}@postgres:5432/gamearr
      REDIS_URL: redis://redis:6379
      FRONTEND_URL: http://localhost:5173
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    environment:
      DB_URL: postgres://gamearr:${POSTGRES_PASSWORD}@postgres:5432/gamearr
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      VITE_API_URL: http://api:3000
    depends_on:
      - api
    ports:
      - "5173:5173"
