services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: gamearr
      POSTGRES_USER: gamearr
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - ../data/redis:/data
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ../data/qbittorrent:/config
      - ../data/downloads:/downloads
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    restart: unless-stopped
    ports:
      - "8070:8080"
    volumes:
      - ../data/sabnzbd:/config
      - ../data/downloads:/downloads
